travis:
  secure:
    BINSTAR_TOKEN: YNjV75Xw8i+IOZ/g747PQF15W+mfmDLhGyxwle4Y1Elcok4MR5XWoi0C7lMmH5m+2hXOa/Ka1EYRRAhfXIiJ/iLjfXs5LLNfvh1blveMRTaRV6dl2GNTVcuY1caa9k/LsG0pIg8TV0K7VrezaYtaRalfDdrhuUEKAvgZIIvvhFPvY1T2+vzB+fF0EJswGPw/2vCGh4bNYK4/N0apYyrZy1MkOd36RoYoChbUf0pnUfkaI0pFjNSwxA18npWr9zsE24LNYeyQsNUDMS1iWGwvXg3VnB5V9CQUWmdi5zS/Rvuu3GoKFi/hIwr7z93tqQDBLeYZQq9/s/6KZ6bliXCOynPBSAg7TaT0L9hAs1OQC11nIdxJBA+c/BLQM1H07YgYe2mXm3VqGz/xjUjp+ovLC08mj5/VrrDQnvrcRP51TRR5HFrBztfeknKaT2kT9O6eW9MVQ9BFkdzm6xfk2s4DvI5pZ0TXgA1L79zcQpWy9xpPr/y4KzkXNje6Rs1FgLA0TqBQWaOQ/8+2Imdl1JzQirO30+9KElDbP0s4SA9i7VpjcJC9FgCFHUjyOt7szXz6pfg2Ls1DQueQYOTw8akHf9rq3+JUQcf4xl3Ghqz8yg5kH9a7zzzsl1anOD1G7+Skvz6Mf62CPsnCzwx0Ex5JbWKAoBAQBDak428TTGV0znI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
